# Site settings
title: Verzijl - Portfolio
email: cjo.verzijl@gmail.com
url: https://cjoverzijl.github.io
description: "Verzijl works on complex physical and financial models, and communicating the results to stakeholders and broader audiences clearly. Interested in solving challenging problems that cross disciplines and borders."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#181818'
  links: '#219ab3'

# Footer settings
footer: CJO Verzijl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/ChristopherVerzijl
  - title: researchgate
    url: https://www.researchgate.net/profile/Christopher_Verzijl
  - title: bitbucket
    url: http://bitbucket.org/cjoverzijl
  - title: github
    url: https://github.com/cjoverzijl

# Build settings
markdown: kramdown
permalink: pretty
