# Site settings
title: Verzijl - Portfolio
email: cjo.verzijl@gmail.com
url: https://cjoverzijl.github.io
description: "Verzijl works on complex physical and financial models, and communicating the results to stakeholders and broader audiences clearly."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#001b33'
  primary-light: '#fcfcfc'
  links: '#219ab3'

# Footer settings
footer: CJO Verzijl

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/ChristopherVerzijl
  - title: researchgate
    url: https://www.researchgate.net/profile/Christopher_Verzijl
  - title: scholar
    url: https://scholar.google.nl/citations?hl=en&user=lSSmi6wAAAAJ&view_op=list_works&sortby=pubdate
  - title: github
    url: https://github.com/cjoverzijl

# Build settings
markdown: kramdown
permalink: pretty

kramdown:  
  parse_block_html: true

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - about.md
  - projects1.md
